# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' zlib version
#' 
version <- function() {
    .Call(`_zlib_version`)
}

#' Compress a raw vector using zlib
#'
#' @param x a raw vector to be compressed
#' @param level the compression level as an integer from -1 to 9, where
#'1 means faster processing and less compression, 9 means the highest
#' compression but slowest processing. 0 perfoms no compression and -1
#' is the default which is a balance of speed and compression 
#' (currently equivalent to 6).
#' 
compress <- function(x, level = -1L) {
    .Call(`_zlib_compress`, x, level)
}

#' Decompress a compressed raw vector using zlib
#' 
#' @param x the compressed raw vector
#' @param wbits a parameter that controls the window size and type of header/trailer used.
#' Default is 15. See Details for more information. 
#' 
#' @section wbits parameter:
#' 
#' The windowBits parameter is the base two logarithm of the maximum window
#' size (the size of the history buffer).  It should be in the range 8..15 for
#' this version of the library. The default value is 15 if inflateInit is used
#' instead. windowBits must be greater than or equal to the windowBits value
#' provided to deflateInit2() while compressing, or it must be equal to 15 if
#' deflateInit2() was not used. If a compressed stream with a larger window
#' size is given as input, inflate() will return with the error code
#' Z_DATA_ERROR instead of trying to allocate a larger window.
#'    
#' windowBits can also be -8..-15 for raw inflate. In this case, -windowBits
#' determines the window size. inflate() will then process raw deflate data,
#' not looking for a zlib or gzip header, not generating a check value, and not
#' looking for any check values for comparison at the end of the stream. This
#' is for use with other formats that use the deflate compressed data format
#' such as zip.  Those formats provide their own check values. If a custom
#' format is developed using the raw deflate format for compressed data, it is
#' recommended that a check value such as an adler32 or a crc32 be applied to
#' the uncompressed data as is done in the zlib, gzip, and zip formats.  For
#' most applications, the zlib format should be used as is. Note that comments
#' above on the use in deflateInit2() applies to the magnitude of windowBits.
#'            
#' windowBits can also be greater than 15 for optional gzip decoding. Add
#' 32 to windowBits to enable zlib and gzip decoding with automatic header
#' detection, or add 16 to decode only the gzip format (the zlib format will
#' return a Z_DATA_ERROR).  If a gzip stream is being decoded, strm->adler is
#' a crc32 instead of an adler32.
#' 
#' @return a raw vector.
#'  
decompress <- function(x, wbits = 15L) {
    .Call(`_zlib_decompress`, x, wbits)
}

